#!/bin/sh
CMD=${LOCAL}/init/cmd
CMD_COMPAT=${LOCAL}/entry/cmd

echo
echo "Container started, running as '$(id)'."
echo

if [ -x "${CMD}" ]; then
  exec "${CMD}"
elif [ -x "${CMD_COMPAT}" ]; then
  echo "${CMD} not found. Make sure your persistent storage is up to date."
  echo "Running ${CMD_COMPAT} instead."
  exec "${CMD_COMPAT}"
else
  echo "${CMD} not found."
  echo "If you just mounted an empty persistent storage on ${LOCAL},"
  echo "extract ${LOCAL}.container.tar.gz, then restart."
  echo
  sleep 86400
  exec tail -f /dev/stderr
fi
