#!/bin/bash
if [ ! -e data/mysql/servers.frm ]; then 
  . /opt/local/mysql/etc/default
  cd ${MYSQL_BASEDIR}
  if [ -x ./scripts/mysql_install_db ]; then 
    ./scripts/mysql_install_db --user=user
  else
    ./bin/mysqld --defaults-file=/opt/local/mysql/etc/my.cnf --initialize-insecure
  fi
  (
    while ! /opt/local/mysql/bin/mysqladmin -u root ping; do sleep 1; done
    /opt/local/mysql/bin/mysql -u root -e "delete from mysql.user where host not in ('127.0.0.1') or user='';"
    /opt/local/mysql/bin/mysql -u root -e "create user 'user'@'127.0.0.1'; grant all privileges on *.* to 'user'@'127.0.0.1' with grant option;"
    /opt/local/mysql/bin/mysql -u root -e "create user 'user'@'localhost'; grant all privileges on *.* to 'user'@'127.0.0.1' with grant option;"
    /opt/local/mysql/bin/mysql -e "flush privileges;"
  ) &
fi
