#!/bin/bash
. /opt/local/mysql/etc/default
if [ ! -e ${MYSQL_BASEDIR}/data/mysql/servers.frm ]; then 
  cd ${MYSQL_BASEDIR}
  mkdir data
  if [ -x ./scripts/mysql_install_db ]; then 
    ./scripts/mysql_install_db --defaults-file=/opt/local/mysql/etc/my.cnf
  else
    ./bin/mysqld --defaults-file=/opt/local/mysql/etc/my.cnf --initialize-insecure
  fi
  (
    while ! mysqladmin -u root ping; do sleep 1; done
    mysql -u root -e "delete from mysql.user;"
    mysql -u root -e "create user 'user'@'127.0.0.1'; grant all privileges on *.* to 'user'@'127.0.0.1' with grant option;"
    mysql -u root -e "create user 'user'@'localhost'; grant all privileges on *.* to 'user'@'localhost' with grant option;"
    mysql -e "flush privileges;"
  ) &
fi
